layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - stars
  #   - pushed
  limit: 6
  exclude:
    archived: false
    forks: false
    projects:
     materialdesignflutter
     androidthings
     supertechninja.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: joshua-mcwilliams
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
     twitter: jtmacsa
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

#topics:
#  - name: CSS
#    web_url: https://github.com/topics/css
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
#
#  - name: Web design
#
#  - name: Sass
#    web_url: https://github.com/topics/sass
#    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
